service: aws-node-express-api-project
frameworkVersion: '3'

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node14'
    define: { 'require.resolve': undefined }
    platform: 'node'
    concurrency: 10
    watch:
      pattern: ['src/**/*.ts'] # match only typescript files in src directory
      ignore: ['temp/**/*']

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs14.x

plugins:
  - serverless-esbuild
  - serverless-offline

functions:
  api:
    handler: src/handler.handler
    events:
      - http:
          method: ANY
          path: '/'
          cors: true
      - http:
          method: ANY
          path: '/{any+}'
          cors: true
